### ISSUE TITLE
targetcli failed to create iscsi portals with errno 22

### ISSUE THREAD

**Issue by JevonQ** [Datera/targetcli#11]
I encountered an error while setting up an iscsi target with targetcli, more precisely, the following error message was outputted when I was creating a portal. I googled it but with no luck. Can anyone give me some help?

/iscsi/iqn.20.../tpg1/portals> create 0.0.0.0 3260
Could not create /sys/kernel/config/target/iscsi/iqn.2003-01.org.linux-iscsi.server-185.x8664:sn.f3202863eec0/tpgt_1/np/0.0.0.0:3260: [Errno 22] Invalid argument: '/sys/kernel/config/target/iscsi/iqn.2003-01.org.linux-iscsi.server-185.x8664:sn.f3202863eec0/tpgt_1/np/0.0.0.0:3260'

/> version
Using configshell version 1.6.1~g020d540
Using rtslib version 3.0.pre4.9~g6fd0bbf
Using targetcli version 3.0.pre4.3~g0fba804

OS version:
$ cat /proc/version
Linux version 3.18.16 (root@server-185) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) ) #2 SMP Wed Jun 17 11:13:37 UTC 2015

Thanks,
Jevon

**Comment by rickysarraf** [comment]
so what was the fix ? @JevonQ

**Comment by JevonQ** [comment]
I have no fix for it. My project was suspended so I did not follow this issue.

**Comment by runner4444** [comment]
I am experiencing this same issue and would like to now how to solve it. This issue should be reopened. I'm on Ubuntu Server 16.04
