### ISSUE TITLE
SRP Target is Not Create 

### ISSUE THREAD

**Issue by raincaller** [Datera/targetcli#22]
OS : Centos 7.2 
Kernel : 3.10.0-327.10.1
Version : targetcli-2.1.fb41-3

Trying to create an SRP target
But Error Message is  " Could not create SRPTFabricModule in configFS " 
What 's the problem?
Help Please

/srpt> info
Fabric module name: srpt
ConfigFS path: /sys/kernel/config/target/srpt
Allowed WWN types: ib
Allowed WWNs list: ib.fe800000000000000002c90300f6fca1, ib.fe800000000000000002c90300f6fca2
Fabric module features: acls
Corresponding kernel module: ib_srpt
/srpt> create 
ib.fe800000000000000002c90300f6fca1  ib.fe800000000000000002c90300f6fca2  wwn=  
/srpt> create wwn=ib.fe800000000000000002c90300f6fca
ib.fe800000000000000002c90300f6fca1      ib.fe800000000000000002c90300f6fca2  
/srpt> create wwn=ib.fe800000000000000002c90300f6fca1
Could not create SRPTFabricModule in configFS
/srpt>

**Comment by agrover** [comment]
this is a targetcli-fb issue, please close and reopen against https://github.com/agrover/targetcli-fb please?

**Comment by raincaller** [comment]
Thank you for reply..
I solved the problem.
Mellanox OFED SRP Target modules is not compatible with ConfigFS.
RPM Package Installed good work

**Comment by ZhangJunT** [comment]
Hi Raincaller, how did you solved the problem?
