### ISSUE TITLE
Could not create Target in configFS

### ISSUE THREAD

**Issue by SteffanCline** [Datera/targetcli#28]
I've googled this particular issue and not really finding any good results on how to resolve it. 

I installed targetcli via yum on CentOS 7 and this is the version in the repo:
`# targetcli -v`
`/usr/bin/targetcli version 2.1.fb49`

Python:
`# python --version`
`Python 2.7.5`

The error comes up when using create.
`/> /qla2xxx create naa.10008c7cffc7ef00`
`Could not create Target in configFS`

Below is the info on my FC
`/> qla2xxx/ info`
`Fabric module name: qla2xxx`
`ConfigFS path: /sys/kernel/config/target/qla2xxx`
`Allowed WWN types: naa`
`Allowed WWNs list: naa.xxxxxxxxxxxxxxx, naa.xxxxxxxxxxxxxxx, naa.xxxxxxxxxxxxxxx, naa.xxxxxxxxxxxxxxx, naa.xxxxxxxxxxxxxxx, naa.xxxxxxxxxxxxxxx, naa.xxxxxxxxxxxxxxx, naa.xxxxxxxxxxxxxxx`
`Fabric module features: acls`
`Corresponding kernel module: tcm_qla2xxx`

I have attached the log but don't see anything that really stands out. [log.txt](https://github.com/Datera/targetcli/files/4006810/log.txt)

I checked per the link http://www.linux-iscsi.org/wiki/Fibre_Channel#Enable_target_mode to ensure that I have initiator mode disabled

`# cat /sys/module/qla2xxx/parameters/qlini_mode`
`disabled`

The kernel modules are loaded.
`# lsmod | grep qla2xxx`
`tcm_qla2xxx            32768  1` 
`target_core_mod       335872  4 tcm_qla2xxx,iscsi_target_mod`
`qla2xxx               634880  1 tcm_qla2xxx`
`scsi_transport_fc      65536  3 bfa,qla2xxx,tcm_qla2xxx`

Suggestions?

**Comment by SteffanCline** [comment]
Anyone know which log file to check as to why it fails? The targtcli log doesn't show any visible errors. I don't see any other in /var/log/messages either.

Decided to check a few other things after Googling. I saw mentions of the configfs being mounted so I checked that too.

`# cat /proc/mounts | grep configfs`
`configfs /sys/kernel/config configfs rw,relatime 0 0`

**Comment by SteffanCline** [comment]
In waiting, I tried CentOS 8 which was an even bigger bust. I wiped that clean and tried again with Fedora 31. Same darn error "Could not create Target in configFS". Anyone??

**Comment by SteffanCline** [comment]
I figure the type of HBA would be good to know. They're a Cavium QLogic BR-1860 QLE2662 which is supported from all I've read. Here are some details.

`# systool -c fc_host -v`
`Class = "fc_host"`
` `
`  Class Device = "host2"`
 ` Class Device path = "/sys/devices/pci0000:00/0000:00:02.0/0000:04:00.0/host2/fc_host/host2"`
 `   active_fc4s         = "0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 "`
`    dev_loss_tmo        = "60"`
`    fabric_name         = "0x0"`
`    issue_lip           = <store method only>`
`    max_npiv_vports     = "255"`
`    maxframe_size       = "0 bytes"`
`    node_name           = "0x20008c7cffc7ef00"`
`    npiv_vports_inuse   = "0"`
`    port_id             = "0x000000"`
`    port_name           = "0x10008c7cffc7ef00"`
`    port_state          = "Linkdown"`
`    port_type           = "Unknown"`
`    speed               = "unknown"`
`    supported_classes   = "Class 3"`
`    supported_fc4s      = "0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x01 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00 "`
`    supported_speeds    = "2 Gbit, 4 Gbit, 8 Gbit, 16 Gbit"`
`    symbolic_name       = "QLogic-1860-2p | 3.2.25.1 |  |  | "`
`    tgtid_bind_type     = "wwpn (World Wide Port Name)"`
`    uevent              = `
`    vport_create        = <store method only>`
`    vport_delete        = <store method only>`
` `
`    Device = "host2"`
`    Device path = "/sys/devices/pci0000:00/0000:00:02.0/0000:04:00.0/host2"`
`      uevent              = "DEVTYPE=scsi_host"`

**Comment by virgilm** [comment]
This repo is not maintained anymore. Please consider using https://github.com/open-iscsi/targetcli-fb
