### ISSUE TITLE
Debian sid dvdburner target saveconfig gives ConfigError: Invalid storage identifier 'pscsi': expected type 'iblock', 'fileio', 'rd_mcp'

### ISSUE THREAD

**Issue by omac777** [Datera/targetcli#9]
On Debian GNU/Linux sid version, I discovered it seems targetcli is not built properly.  Once entered in targetcli shell and running:
/> version
Cannot find configshell version. The configshell package has probably not been built properly from either the git repository or a public tarball.
Cannot find rtslib version. The rtslib package has probably not been built properly from either the git repository or a public tarball.
Cannot find targetcli version. The targetcli package has probably not been built properly from either the git repository or a public tarball.
/> 

When attempting to use targetcli's saveconfig, I keep on getting the following error:
"
ConfigError: Invalid storage identifier 'pscsi': expected type 'iblock', 'fileio', 'rd_mcp'
"
Even worse, I can't even exit the targetcli after getting this error.  I need to resort to ctrl-Z to get the process in background and do a kill from there.

The scenario is when I attempt to create a pscsi target for a dvd burner.
I actually attempted to create an iblock and fileio target using the same device /dev/sr0 and they also failed to use /dev/sr0 because it's a dvd burner:
Device is not a TYPE_DISK block device.
Device /dev/sr0 is a block device, but not of TYPE_DISK.

Cheers,
David Marceau

Exact details follow:
 targetcli
targetcli GIT_VERSION (rtslib GIT_VERSION)
Copyright (c) 2011-2014 by Datera, Inc.
All rights reserved.

/backstores> ls
o- backstores ................................................................................................................ [...]
  o- fileio ..................................................................................................... [0 Storage Object]
  o- iblock ..................................................................................................... [0 Storage Object]
  o- pscsi ...................................................................................................... [0 Storage Object]
  o- rd_mcp ..................................................................................................... [0 Storage Object]
/backstores> ls
o- backstores ................................................................................................................ [...]
  o- fileio ..................................................................................................... [0 Storage Object]
  o- iblock ..................................................................................................... [0 Storage Object]
  o- pscsi ...................................................................................................... [0 Storage Object]
  o- rd_mcp ..................................................................................................... [0 Storage Object]
/backstores> pwd
/backstores
/backstores> cd backstores
No such path /backstores/backstores
/backstores> ls
o- backstores ................................................................................................................ [...]
  o- fileio ..................................................................................................... [0 Storage Object]
  o- iblock ..................................................................................................... [0 Storage Object]
  o- pscsi ...................................................................................................... [0 Storage Object]
  o- rd_mcp ..................................................................................................... [0 Storage Object]
/backstores> iblock/ create name=dvd_backend dev=/dev/sr0
Generating a wwn serial.
Device is not a TYPE_DISK block device.
/backstores> fileio/ create name=dvd_backend dev=/dev/sr0
Missing required parameter file_or_dev
/backstores> fileio/ create name=dvd_backend file_or_dev=/dev/sr0
Generating a wwn serial.
Using buffered mode.
Device /dev/sr0 is a block device, but not of TYPE_DISK.
/backstores> ls
o- backstores ................................................................................................................ [...]
  o- fileio ..................................................................................................... [0 Storage Object]
  o- iblock ..................................................................................................... [0 Storage Object]
  o- pscsi ...................................................................................................... [0 Storage Object]
  o- rd_mcp ..................................................................................................... [0 Storage Object]
/backstores> exit
There are unsaved configuration changes.
If you exit now, configuration will not be updated and changes will be lost upon reboot.
Type 'exit' if you want to exit anyway: yes
Aborted exit, use 'saveconfig' to save the current configuration.
/backstores> exit
There are unsaved configuration changes.
If you exit now, configuration will not be updated and changes will be lost upon reboot.
Type 'exit' if you want to exit anyway: exit
root@righteous:/home/loongson# targetcli
targetcli GIT_VERSION (rtslib GIT_VERSION)
Copyright (c) 2011-2014 by Datera, Inc.
All rights reserved.

/backstores> cd backstores
No such path /backstores/backstores
/backstores> pscsi/ create name=pscsi_backend dev=/dev/sr0
Note: block backstore recommended for SCSI block devices
Created pscsi storage object pscsi_backend using /dev/sr0
/backstores> cd pscsi/pscsi_backend 
/backstores/p...pscsi_backend> /iscsi create
Created target iqn.2003-01.org.linux-iscsi.righteous.x8664:sn.9bcd43428b11.
Selected TPG Tag 1.
Created TPG 1.
/backstores/p...pscsi_backend> cd /iscsi/iqn.2003-01.org.linux-iscsi.righteous.x8664:sn.9bcd43428b11/tpg1/
/iscsi/iqn.20...43428b11/tpg1> luns/ create /backstores/pscsi/pscsi_backend 
Selected LUN 0.
Created LUN 0.
/iscsi/iqn.20...43428b11/tpg1> set attribute authentication=0 demo_mode_write_protect=0 generate_node_acls=1 cache_dynamic_acls=1
Parameter demo_mode_write_protect is now '0'.
Parameter authentication is now '0'.
Parameter generate_node_acls is now '1'.
Parameter cache_dynamic_acls is now '1'.
/iscsi/iqn.20...43428b11/tpg1> cd /
/> ls
o- / ......................................................................................................................... [...]
  o- backstores .............................................................................................................. [...]
  | o- fileio ................................................................................................... [0 Storage Object]
  | o- iblock ................................................................................................... [0 Storage Object]
  | o- pscsi .................................................................................................... [1 Storage Object]
  | | o- pscsi_backend ........................................................................................ [/dev/sr0 activated]
  | o- rd_mcp ................................................................................................... [0 Storage Object]
  o- ib_srpt ........................................................................................................... [0 Targets]
  o- iscsi .............................................................................................................. [1 Target]
  | o- iqn.2003-01.org.linux-iscsi.righteous.x8664:sn.9bcd43428b11 ......................................................... [1 TPG]
  |   o- tpg1 ............................................................................................................ [enabled]
  |     o- acls ........................................................................................................... [0 ACLs]
  |     o- luns ............................................................................................................ [1 LUN]
  |     | o- lun0 ................................................................................. [pscsi/pscsi_backend (/dev/sr0)]
  |     o- portals ..................................................................................................... [0 Portals]
  o- loopback .......................................................................................................... [0 Targets]
  o- qla2xxx ........................................................................................................... [0 Targets]
  o- tcm_fc ............................................................................................................ [0 Targets]
  o- vhost ............................................................................................................. [0 Targets]
/> saveconfig 
WARNING: Saving righteous current configuration to disk will overwrite your boot settings.
The current target configuration will become the default boot config.
Are you sure? Type 'yes': yes
Saving new startup configuration
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 990, in run_interactive
    self._cli_loop()
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 820, in _cli_loop
    self.run_cmdline(cmdline)
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 934, in run_cmdline
    self._execute_command(path, command, pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/configshell/shell.py", line 909, in _execute_command
    result = target.execute_command(command, pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/targetcli/ui_node.py", line 103, in execute_command
    pparams, kparams)
  File "/usr/lib/python2.7/dist-packages/configshell/node.py", line 1416, in execute_command
    result = method(*pparams, **kparams)
  File "/usr/lib/python2.7/dist-packages/targetcli/ui_root.py", line 68, in ui_command_saveconfig
    CliConfig.save_running_config()
  File "/usr/lib/python2.7/dist-packages/targetcli/cli_config.py", line 65, in save_running_config
    config.load_live()
  File "/usr/lib/python2.7/dist-packages/rtslib/config.py", line 562, in load_live
    source=source, allow_new_attrs=True)
  File "/usr/lib/python2.7/dist-packages/rtslib/config.py", line 190, in _load_parse_tree
    token = self.validate_obj(token, cur)
  File "/usr/lib/python2.7/dist-packages/rtslib/config.py", line 390, in validate_obj
    ", ".join(expected_val_types)))
ConfigError: Invalid storage identifier 'pscsi': expected type 'iblock', 'fileio', 'rd_mcp'
/> 

/> version
Cannot find configshell version. The configshell package has probably not been built properly from either the git repository or a public tarball.
Cannot find rtslib version. The rtslib package has probably not been built properly from either the git repository or a public tarball.
Cannot find targetcli version. The targetcli package has probably not been built properly from either the git repository or a public tarball.
/>

**Comment by rickysarraf** [comment]
On Friday 03 April 2015 09:31 PM, David Marceau wrote:
> Exact details follow:
> targetcli
> targetcli GIT_VERSION (rtslib GIT_VERSION)
> Copyright (c) 2011-2014 by Datera, Inc.
> All rights reserved.
Please use the one from experimental. The version in sid is broken. I
need to update it. But for now, use the experimental version.
https://packages.debian.org/source/experimental/targetcli

-- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."

**Comment by omac777** [comment]
Thank you rickysarraf.

I assumed debian sid had the latest git commits.  I was wrong.  I got the latest from github for configshell, rtslib and targetcli and all my issues disappeared.  Cheers.
